In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("cardio_train.csv", sep=';')
df

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

### 1 . How many rows ans columns are present in datasets?

In [5]:
df.shape

(70000, 13)

### 2. What are the names of all columns?

In [6]:
df.columns

Index(['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio'],
      dtype='object')

### 3. See the first 20 Entries

In [7]:
df.head(20)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
5,8,21914,1,151,67.0,120,80,2,2,0,0,0,0
6,9,22113,1,157,93.0,130,80,3,1,0,0,1,0
7,12,22584,2,178,95.0,130,90,3,3,0,0,1,1
8,13,17668,1,158,71.0,110,70,1,1,0,0,1,0
9,14,19834,1,164,68.0,110,60,1,1,0,0,0,0
10,15,22530,1,169,80.0,120,80,1,1,0,0,1,0
11,16,18815,2,173,60.0,120,80,1,1,0,0,1,0
12,18,14791,2,165,60.0,120,80,1,1,0,0,0,0
13,21,19809,1,158,78.0,110,70,1,1,0,0,1,0
14,23,14532,2,181,95.0,130,90,1,1,1,1,1,0
15,24,16782,2,172,112.0,120,80,1,1,0,0,0,1
16,25,21296,1,170,75.0,130,70,1,1,0,0,0,0
17,27,16747,1,158,52.0,110,70,1,3,0,0,1,0
18,28,17482,1,154,68.0,100,70,1,1,0,0,0,0
19,29,21755,2,162,56.0,120,70,1,1,1,0,1,0

### 4. See the last 10 Entries

In [8]:
df.tail(10)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
69990,99986,15094,1,168,72.0,110,70,1,1,0,0,1,1
69991,99988,20609,1,159,72.0,130,90,2,2,0,0,1,0
69992,99990,18792,1,161,56.0,170,90,1,1,0,0,1,1
69993,99991,19699,1,172,70.0,130,90,1,1,0,0,1,1
69994,99992,21074,1,165,80.0,150,80,1,1,0,0,1,1
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

### 5. what is number of observation in datasets ?

In [9]:
df.shape[0]

70000

### 6. what is the number of columns in datasets ?

In [10]:
df.shape[1]

13

### 7. What is datatype of each columns ?

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

### 8. Summarize the Dataframe

In [12]:
df.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

### 9. Are there any missing values?

In [14]:
df.isnull()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,False,False,False,False,False,False,False,False,False,False,False,False,False
69996,False,False,False,False,False,False,False,False,False,False,False,False,False
69997,False,False,False,False,False,False,False,False,False,False,False,False,False
69998,False,False,False,False,False,False,False,False,False,False,False,False,False
69999,False,False,False,False,False,False,False,False,False,False,False,False,False

### 10. How many patients have cardiovascular disease?

In [19]:
df[df['cardio'] == 1]['cardio'].count()

np.int64(34979)

### 11. How many patients do not have cardiovascular disease?

In [20]:
df[df['cardio']==0]['cardio'].count()

np.int64(35021)

### 12. What is the minimum and maximum age?

In [25]:
df['age_year'] = df['age']/365
df['age_year']

0        50.391781
1        55.419178
2        51.663014
3        48.282192
4        47.873973
           ...
69995    52.712329
69996    61.920548
69997    52.235616
69998    61.454795
69999    56.273973
Name: age_year, Length: 70000, dtype: float64

In [26]:
df['age_year'].min()

29.583561643835615

In [27]:
df['age_year'].max()

64.96712328767123

### 13. What is Avg age

In [28]:
df['age_year'].mean()

np.float64(53.33935839530333)

## 14. Count total Male and Female

In [31]:
# 1-women and 2-men
male_count = df[df['gender']==2]['gender.count()
male_count

np.int64(24470)

In [32]:
female_count = df[df['gender']==1]['gender'].count()
female_count

np.int64(45530)

### 15. Which gender has more cardiovascular disease?

In [33]:
if female_count>male_count:
    print("Females has more cardiovascular")
else:
    print("Male has more cardiovascular")

Females has more cardiovascular

### 16. What is average height and weight?

In [34]:
print("Average Height:", df["height"].mean())
print("Average Weight:", df["weight"].mean())

Average Height: 164.35922857142856
Average Weight: 74.20569

### 17. Find tallest and shortest patient

In [35]:
df["height"].max()

250

In [36]:
df["height"].min()

55

### 18. Create BMI and analyze disease.

In [39]:
df['BMI'] = (df['weight'])/((df['height']/100)**2)
df['BMI']

0        21.967120
1        34.927679
2        23.507805
3        28.710479
4        23.011177
           ...
69995    26.927438
69996    50.472681
69997    31.353579
69998    27.099251
69999    24.913495
Name: BMI, Length: 70000, dtype: float64

### 19. Average systolic BP (ap_hi) and diastolic BP (ap_lo).

In [40]:
df['ap_hi'].mean()

np.float64(128.8172857142857)

In [41]:
df['ap_lo'].mean()

np.float64(96.63041428571428)

### 20. Which gender has more smokers ?

In [43]:
male_smoker = df[df['gender'] == 2]['gender'].count()
male_smoker

np.int64(24470)

In [44]:
female_smoker = df[df['gender'] == 1]['gender'].count()
female_smoker

np.int64(45530)

In [45]:
if male_smoker>female_smoker:
    print("Male")
else:
    print("Female")

Female